setup.py

Version should be less than 1.0.0 until interfaces are deemed
stable.

Set version to appropriate value for development

---

docs/conf.py
docs/garbage-collect.rst
docs/index.rst
pubtools/pulp/task.py
pubtools/pulp/tasks/garbage_collect.py
requirements.txt
setup.py
tests/test_pulp_task.py
tests/test_task_interface.py
tox.ini

Initial version of "command reference" docs.
Each command should be documented on its own page.
This documentation can be (partially) generated from the
ArgumentParser objects, to document all supported arguments with
their help text.
Some minor refactoring was needed to ensure that ArgumentParser
objects can be created & accessed without running tasks.
Most notably, the usage of attrs was dropped as it mainly
seems to be getting in the way, and we don't much benefit from
any attrs features here.

Extend, fix & add docs with sphinx-argparse

---

pubtools/_pulp/tasks/clear_repo.py
pubtools/_pulp/tasks/garbage_collect.py
requirements.txt

This is no longer required when iterating over search results.

cleanup: drop usage of deprecated as_iter

---

docs/index.rst
docs/set-maintenance.rst
pubtools/_pulp/tasks/set_maintenance/__init__.py
pubtools/_pulp/tasks/set_maintenance/base.py
pubtools/_pulp/tasks/set_maintenance/set_maintenance_off.py
pubtools/_pulp/tasks/set_maintenance/set_maintenance_on.py
setup.py
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_off.jsonl
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_off.txt
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_off_with_regex.jsonl
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_off_with_regex.txt
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_off_with_repo_not_in_maintenance.jsonl
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_off_with_repo_not_in_maintenance.txt
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_on.jsonl
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_on.txt
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_on_with_regex.jsonl
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_on_with_regex.txt
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_on_with_repo_not_exists.jsonl
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_on_with_repo_not_exists.txt
tests/set_maintenance/test_base.py
tests/set_maintenance/test_set_maintenance.py
tests/shared/test_task_interface.py

Two commands are included:
1. pubtools-pulp-maintenance-on: enable maintenance mode
2. pubtools-pulp-maintenance-off: disale maintenance mode
Both commands accepts repo ids and repo regex pattern as input. For enable
maintenance mode, if repo ids are passed, then it first checks if the repo
exists or not by querying pulp server with repo ids.
The general workflow for set maintenance is:
1. get maintenance report from pulp server
2. make changes to report according to enable/disable
3. upload result report to pulp and publish

Introduce set maintenance commands

---

pubtools/_pulp/task.py
tests/shared/test_pulp_task.py
tests/shared/test_pulp_task_logging.py

Because "--debug --debug --debug" is annoying to write.
Giving a short alias allows e.g. "-ddd" to work.

logging: add -d alias for --debug

---

pubtools/_pulp/tasks/set_maintenance/set_maintenance_on.py

The reason why --repo-url-regex option isn't working is because,
for validation purpose, we add type=re.compile to that option, make
sure it's a valid pattern and passed it to make Criteria object directly,
which isn't supported.
Now passes RE.Pattern object's pattern to it.

fix couldn't search distributors while setting maintenance mode on

---

docs/publish.rst
pubtools/_pulp/tasks/publish.py
pubtools/_pulp/tasks/set_maintenance/base.py
tests/publish/test_publish.py
tests/set_maintenance/test_set_maintenance.py

The advantage of accepting comma separated argument is, the command
fails immediately if space is used. In the opposite, if space is used
as the separator and if user wrongly used comma, then the command won't fail
until certain stage, or even succeeds with wrong results.

Make repo-ids option accept comma separated argument

---

README.md

It's convenient to have a link directly to PyPI from the
project's README, to advertise that the project is available there
and also at a glance show the latest released version.

README: add badge for PyPI

---

CHANGELOG.md
pubtools/_pulp/ud.py

Older versions of concurrent.futures.ThreadPoolExecutor didn't had
default number of workers and has to passed explicitly to __init__
This patch adds the max_workers param during initialization to be
compatible with previous versions of ThreadPoolExecutor.

Add max_worker param to UDClient Executor for backward compatibility

---

CHANGELOG.md
pubtools/_pulp/ud.py
tests/ud/test_ud_cache_client.py

Product IDs are provided as integers.  os.path.join does not accept
integers, so make sure to stringify all IDs while assembling URLs.
Autotests would have caught this, but were inaccurately providing
strings rather than integers as product IDs.

Fix crash when flushing UD cache for engproduct

---

constraints-legacy.txt
tests/set_maintenance/test_set_maintenance.py
tests/shared/test_pulp_task.py
tox.ini

There are some constraints applied on the dependencies of dependecnies
e.g. jsonschema in pubtools-pulplib via constraints.txt. However, those
constraints are not followed here and the installation for Python 2.7
fails. Hence, addind a constraints.txt file to include the constraints
form the dependencies and using that file in tox.ini for Python 2.7
installation.

Constraints from dependencies are included for Python 2.7

---

.travis.yml
CHANGELOG.md
pubtools/_pulp/tasks/clear_repo.py
requirements.txt
test-requirements.txt
tests/clear_repo/test_clear_repo.py

Clear-repo currently sends raw dicts to pushcollector.
This patch updates to send pushitem objects defined in the
pushsource library to send it to push collector instead of
raw dicts.

Clear-repo sends pushitem objects to the pushcollector

---

.travis.yml

Rust compiler isn't a part of the xenial
and is needed for building cryptography wheel
that is dependency of pyOpenSSL via edgegrid-python->fastpurge.

Move to ubuntu:bionic env. of travis

---

CHANGELOG.md
pubtools/_pulp/tasks/publish.py
tests/publish/test_publish.py

Arg. repo-ids can be specified multiple times
in publish task. Previous "Comma separated repos"
behavior is retained.
E.g. --repo-ids 'a,b,c' will result in publishing
the same repos as in case --repo-ids 'a' --repo-ids 'b,c'

Arg. repo-ids can be specified multiple times [RHELDST-5455]

---

CHANGELOG.md
pubtools/_pulp/services/pulp.py
requirements.txt
tests/shared/test_pulp_task.py

All commands now support 'pulp-throttle' option.
This option allows to enqueue or run specified maximum
number of Pulp pask at one moment.

Add 'pulp-throttle' option to CLI of commands [RHELDST-441]

---

CHANGELOG.md
pubtools/_pulp/ud.py
requirements.txt

This is a good idea because:
- the name will be reused in any created threads, so we can
figure out which code created which thread
- the name will appear in prometheus metrics

refactor: give executor a meaningful name

---

.gitignore
pubtools/_pulp/arguments.py
pubtools/_pulp/tasks/clear_repo.py
tests/clear_repo/test_clear_repo.py
tests/logs/clear_repo/test_clear_repo/test_clear_repo_multiple_content_types.jsonl
tests/logs/clear_repo/test_clear_repo/test_clear_repo_multiple_content_types.txt
tests/shared/test_arguments.py

Overview
=======
Allow the `--content-type` option to `clear-repo` to be specified multiple times. Each instance of `--content-type` still conforms to the current behavior of being a comma-separated list of content types.
Approach
-------------
Add a new [argparse.Action](https://docs.python.org/3/library/argparse.html#argparse.Action) subclass called `SplitAndExtend` that can be re-used for any situation like this and allows for delimiters other than `","` to be used (though `","` is the default). This Action class is now used in `ClearRepo#add_args` to configure the parser to accept multiple instances of `--content-type`
The `ClearRepo#content_type` property accessor has been updated so that it no longer has to do string splitting and instead just returns the accumulated list parsed …

Clear repo content type multi instance

---

.pre-commit-config.yaml
tests/garbage_collect/test_garbage_collect.py
tests/shared/test_pulp_task.py
tox.ini

This commit drops the black code formatting tool from "tox -e static" as
well as refreshing the black version used by pre-commit (and letting
black fix a couple of files).  Instead of running black within tox,
let's have the pre-commit-ci service take care of it.
The motivation here is that I want to pin all dependencies used by tox.
But if that includes black, then updating the pins might need to include
reformatting files, and our CI doesn't implement anything like that.
However, pre-commit-ci itself already implements everything needed here,
so if we shift responsibility to that service then we don't need
anything more.

ci: update black version, drop from 'static', move to pre-commit-ci

---

requirements.in
requirements.txt
test-requirements.txt
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_off.txt
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_off_with_regex.txt
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_off_with_repo_not_in_maintenance.txt
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_on.txt
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_on_with_regex.txt
tests/logs/set_maintenance/test_set_maintenance/test_maintenance_on_with_repo_not_exists.txt
tests/set_maintenance/test_set_maintenance.py

This pulplib update is best combined with some test updates because:
- some log-based tests need testdata updates due to logging changes in
pulplib
- on the fake client, upload_history was deprecated, so let's remove its
use from the couple of related tests. It arguably shouldn't have been
there in the first place anyway, as it is an implementation detail of
the client that calling set_maintenance involves an upload.

Bump pubtools-pulplib requirement

---

pubtools/_pulp/services/pulp.py
tests/shared/test_pulp_task.py

Task throttle in Pulp client is modified with the --pulp-throttle
option in the PulpClientService. This throttle value will now be
modified with the PULP_THROTTLE environment variable as well. It
should be defined before invoking the task and the client service
will pick the throttle value from the env if it's not specified
as the --pulp-throttle option.

Add PULP_THROTTLE env variable for task throttle in Pulp client

---

pubtools/_pulp/services/fakepulp.py
pubtools/_pulp/services/pulp.py
pubtools/_pulp/task.py
tests/conftest.py
tests/data/sample-modules.yaml
tests/fake/test_fake_persistence.py
tests/shared/test_pulp_task.py

This change makes the --pulp-fake argument much more useful by:
- having it save and load state as each task is run
- having it seed a bit of common state (e.g. existence of
all-rpm-content repo) if there is no prior state
The intent is to make running the tasks against a fake usable in
situations where it previously wasn't, and also make it possible to
view the changes made by a task. It's similar in concept to
developing a service against a local sqlite DB while a remote
DB is used in production.
As an example, if I run the maintenance-on command like this:
$ pubtools-pulp-maintenance-on --pulp-fake --repo-ids myrepo
[INFO    ] Get maintenance report: started
[WARNING ] Using a fake Pulp client, no changes will be made to Pulp!
[INFO    ] Get maintenance report: finished
[INFO    ] …

Add persistence to --pulp-fake

---

pubtools/_pulp/tasks/common.py
pubtools/_pulp/tasks/publish.py

I'm currently working on pubtools-pulp-push. The push task will need to
publish repos and flush caches and ideally would use exactly the same
arguments and behavior as the existing publish task.
Let's refactor a little so that most of the publish logic can be easily
shared across multiple tasks.

refactor: move some behavior from 'publish' task to 'common'

---

tests/fake/test_fake_persistence.py

In tests outside of pubtools-pulplib, it is a bit risky to compare
expected results against precise *Unit instances. The problem is that if
pubtools-pulplib gains support for any new fields, and the fake client
sets those fields to non-default values, then the test would start to
fail as the objects would no longer be precisely equal.
The effect is that such a test may not be forwards-compatible with
newer versions of pubtools-pulplib.
Fix it up by not comparing details we don't care about. In this specific
case, we're only trying to do a sanity check of modulemds we've
uploaded, so we don't need to check every field.

tests: fix a non-forwards-compatible test

---

pubtools/_pulp/services/fakepulp.py
tests/fake/test_fake_persistence.py

In typical cases, many fields on repo and unit objects will simply be
using their default values.
Don't persist those fields; it keeps the files cleaner, and also works
better in cases where a new version of pubtools-pulplib changes the
default value for a field.

Make --pulp-fake persistence cleaner

---

pubtools/_pulp/step.py
pubtools/_pulp/task.py
tests/step/test_step_logging.py

I'm currently working on pubtools-pulp-push and finding that I would
like to write some push steps as generators. For example, the
"Calculate checksums" `@step` can accept items without checksums as input,
and yield items with checksums as output, without having to eagerly load
all items.
`@step` decorator did not formerly support this; add support for it here.
This is not currently used from any task. I've split this refactor off
from the main pubtools-pulp-push work to reduce the size of the upcoming
PR for that.

refactor: make @step decorator support generators

---

tests/fake/test_fake_persistence.py

The fake is supposed to support automatically creating the directory for
the state file. However, this is not tested if we put the state file
directly in "tmpdir" during tests, since that dir already exists.

tests: fix one uncovered path for --pulp-fake

---

pubtools/_pulp/hooks.py
pubtools/_pulp/tasks/common.py
requirements.in
setup.py
tests/push/test_push.py

A hook, "task_pulp_flush", is now specified and called when
pubtools-pulp-push completes publishing all repositories. Hook
implementations may now subscribe to these events to flush pulp-derived
caches and datastores.

Add pulp flush  hook [RHELDST-7309]

---

pubtools/_pulp/tasks/push/items/file.py
requirements.in
requirements.txt
test-requirements.txt
tests/data/staged-mixed/staged.yaml
tests/logs/push/test_push/test_typical_push.pulp.yaml
tests/logs/push/test_push/test_update_push.pulp.yaml
tests/logs/push/test_push_copy_fails/test_push_copy_fails.txt

version, display_order fields can now be passed onto Pulp, fixing
one of the TODOs. With the latest version of pubtools-pulplib, this will
result in the setting of ud_file_release_mappings_2 repo note during
publish.
(note the comment's reference to content ISOs is outdated, as we decided
that content ISOs won't be ported over to this code.)

push: support the remainder of File mutable fields

---

requirements.in
requirements.txt
test-requirements.txt

2.24.0 fixed a crash bug when uploading large files. It's important to
ensure we have that fix since it's known to affect the push command.

deps: bump minimum version of pulplib

---

pubtools/_pulp/tasks/push/command.py
pubtools/_pulp/tasks/push/phase/base.py
pubtools/_pulp/tasks/push/phase/collect.py
pubtools/_pulp/tasks/push/phase/context.py
pubtools/_pulp/tasks/push/phase/end_pre_push.py
pubtools/_pulp/tasks/push/phase/publish.py
tests/push/test_context_counts.py

Track queue events to get an idea of the progress of each phase.
For each phase, by looking at how many items have been put onto the
queue and how many have been taken out, we can figure out the overall
progress of the phase.
This progress info will be logged at a configurable interval as push runs
(every 5 minutes by default). The logging includes both a visual
component (progress bars) and structured metrics which can be gathered
into JSONL logs.
The primary goal of this logging is to make it clear which of the phases
acts as a bottleneck and could benefit from performance improvements or
tuning.

Add progress tracking onto push phases [RHELDST-8331]

---

pubtools/_pulp/tasks/push/items/base.py
pubtools/_pulp/tasks/push/phase/base.py
pubtools/_pulp/tasks/push/phase/load_sums.py
tests/push/test_load_sums.py

Testing shows this step to be a bottleneck. Fix the TODO about
parallelizing the checksum calculation. Also make it possible for the
phase to pass through objects which already have checksums as quickly as
possible, so that later phases can start processing those items
earlier.
Some features were added to Phase base class to support this. Other
phases are likely to get similar refactors.

push: parallelize checksum calculation

---

pubtools/_pulp/tasks/push/phase/context.py

Without this, when running in Pub there is no way to customize
the width of the progress bar. (shutil.get_terminal_size already
respects COLUMNS, but it's not available for python 2.)

Tweak progress logger to look at COLUMNS by default

---

pubtools/_pulp/tasks/push/phase/base.py
pubtools/_pulp/tasks/push/phase/context.py
pubtools/_pulp/tasks/push/phase/load_items.py
tests/push/test_context_counts.py

Progress bars should fill up as push items are processed; however,
the total push item count is not known initially which could cause the
progress bars to be misleading.
Fix this by:
- marking the progress bars with '???' while the count is unknown
(indicating an estimate)
- using the real item count (passed around via context) once it becomes
known at the end of the first phase

Improve accuracy of progress logging by tracking item count

---

pubtools/_pulp/tasks/push/copy.py
pubtools/_pulp/tasks/push/items/base.py
pubtools/_pulp/tasks/push/phase/associate.py
pubtools/_pulp/tasks/push/phase/base.py
pubtools/_pulp/tasks/push/phase/query_pulp.py
pubtools/_pulp/tasks/push/phase/update.py
pubtools/_pulp/tasks/push/phase/upload.py

As a holdover from the older generator-based implementation, the logic
in these phases was written in a way such that no items would be output
until all items had been received on the input. This unnecessarily
blocks later phases.
Rewrite them to remove the unnecessary blocking. In each case a refactor
is done so that the phase is able to make use of put_future_output(s),
similarly as done for the checksum phase in fa8cedbd84.

Improve pipelining of upload, update, query & associate push phases

---

pubtools/_pulp/tasks/push/phase/base.py
tests/push/test_phase_error_logs.py

Errors can occur asynchronously when put_future_output is used.
A comment here reasoned that this should not be logged in the error
handling callback because re-raising the exception will cause it
to propagate elsewhere and appropriate logging will happen there.
That reasoning was not correct for all cases. When the error was
re-raised, we'd be putting the phase into a state where __get_input
would raise PhaseInterrupted and __future_puts would raise the original
exception. There is no guarantee which one happens first, as it depends
how the phase implements run(). If the former happened first, the
original exception which caused the interruption would be silently lost.
Update the error handling so that the exception will always be logged in
this scenario.

push: fix an error handling mistake which could swallow exceptions

---

pubtools/_pulp/tasks/push/phase/base.py

Theoretically, if a phase executes very quickly, thread.start() here
could run the entire phase to completion and log the "finished" message
before the very next call to log_start which logs the "started" message.
Make sure we log_start before starting the thread to prevent this.
This probably only affects tests, where trivial phase implementations
with a near-empty run() method might be used.

push: fix phase start logs out of order in edge cases

---

pubtools/_pulp/tasks/push/items/base.py
tests/push/test_item_state_checks.py

When we upload or update an item in Pulp, even if the Pulp API says it
succeeded, we should still double-check the new state of the item to
verify that it had the desired impact. (i.e. if we uploaded an item then
it should be in at least one repo; if we updated an item then it should
not require any further updates.
Fixes a couple of TODOs.

push: add checks on the outcome of item uploads & updates

---

pubtools/_pulp/tasks/push/items/rpm.py
tests/push/test_rpm_bad_filename.py

If RPM filenames are not valid such that an NVR can't be extracted, we
would previously generate an error which would only make sense to
developers. Let's raise a more user-friendly error explaining the
problem. Fixes one TODO.

push: improve error handling on RPM naming error

---

pubtools/_pulp/tasks/push/phase/associate.py
tests/push/test_associate_item_order.py

We want to ensure that RPMs are always associated into target repos only
after any corresponding modulemds. Previously, the simplistic solution
to this was simply to not associate *anything* until *all* uploads had
completed, but that causes unnecessary blocking in some cases and
potentially wastes a lot of time for pushes which don't even use RPMs or
modules.
With a minor refactor we can do a little better: make associate process
RPMs last, only after all other items have made it into the phase. Fixes
a TODO.
This could still be improved further by tracking information on which
modules/RPMs correspond to each other and in which repos, but the
performance vs complexity trade-off isn't clear right now.

push: reduce modulemd-related blocking in associate

---

pubtools/_pulp/tasks/push/phase/context.py
tests/push/test_push.py

Add a tunable for the max size of queues used to pass items between
phases. The intent is to provide a way of reducing memory usage.

push: make queue size adjustable

---

pubtools/_pulp/tasks/clear_repo.py
pubtools/_pulp/tasks/push/copy.py
pubtools/_pulp/tasks/push/items/base.py
pubtools/_pulp/tasks/push/items/comps.py
pubtools/_pulp/tasks/push/items/direct.py
pubtools/_pulp/tasks/push/items/erratum.py
pubtools/_pulp/tasks/push/items/file.py
pubtools/_pulp/tasks/push/items/modulemd.py
pubtools/_pulp/tasks/push/items/productid.py
pubtools/_pulp/tasks/push/items/rpm.py

Tasks dealing with many items have been running into some memory usage
issues. Slots-based classes are expected to reduce memory pressure, and
we don't seem to be impacted by the caveats about this in the attrs
docs, so let's use them.

Use slots for all attr.s classes

---

pubtools/_pulp/tasks/push/items/erratum.py
tests/push/test_pulperratumpushitem.py

Due to the errata-specific logic of "if unit changes in any repo,
republish all of them", we could end up trying to publish & cache flush
the all-rpm-content repo here if an erratum unit existed in that repo.
Publish wouldn't be a problem as the pulp client is smart enough to
realize that's a no-op, but cache flush would fail.
Add a condition to avoid doing any publish handling for those repos.

push: fix attempting to flush UD cache for all-rpm-content

---

pubtools/_pulp/services/__init__.py
pubtools/_pulp/services/cachingpulp.py
pubtools/_pulp/tasks/push/command.py
pubtools/_pulp/tasks/push/items/base.py
tests/push/conftest.py
tests/shared/test_pulp_cache.py

Fixes a performance TODO. During copy phase of push, we may be
repeatedly calling get_repository for the same repo. Add a bit of
caching around these calls to reduce redundant calls to Pulp.

Add some caching onto Pulp repo lookups

---

pubtools/_pulp/tasks/push/phase/base.py
tests/push/test_phase_limits.py

future_puts here was previously constructed using f_and.
Problem: we can potentially end up with thousands of wrapped
futures in that case, and depending on the order they're resolved, this
can cause a stack overflow when a completion callback is invoked.
This would be most common in the case where a slow operation was
followed by thousands of fast operations.
Fix it by rewriting the code to avoid any deep chain of futures like
that. Since f_and was used to get the "cancel futures when no longer
needed" behavior, that behavior now needs to be implemented explicitly.

Fix a scaling issue with put_future_output

---

pubtools/_pulp/tasks/push/phase/base.py
pubtools/_pulp/tasks/push/phase/context.py
tests/push/test_phase_batching.py

In testing of a large push I noted that the "query pulp" phase was often
querying a very small batch, or even a single file at a time.
That would be because the small batch timeout of 0.1 didn't make sense
any more after refactoring the phases to use put_future_outputs.
With that refactor, each iteration of iter_input_batched would tend to
be very fast since the real work is done asynchronously. It would also
not be blocked by a full output queue. This meant it would be too easy
for the phase to always keep up with the input queue and process only
0.1 seconds worth of items at a time, leading to Pulp searches of only a
couple of items.
Make it smarter by using the output queue size to generate some
backpressure. We will apply a small timeout if the output queue is
empty, and a large …

push: make batch timing smarter, more self-tuning

---

pubtools/_pulp/tasks/push/phase/collect.py
tests/push/test_collect_duplicates.py
tests/push/test_push.py

If we're running fast enough, we might end up calling update_push_items
with the "same" item at multiple states, e.g. PENDING when we first
discover it and then EXISTS if we were already able to figure out the
item exists in Pulp.
In that case, we should only include the latest version of the item.
It's important because Pub's collector backend will crash otherwise as
it does not expect to see duplicate items like that.

push: make collect phase filter out duplicates

---

pubtools/_pulp/tasks/push/items/base.py
pubtools/_pulp/tasks/push/items/file.py
pubtools/_pulp/tasks/push/items/rpm.py
tests/data/staged-mixed/dest2/RPMS/walrus-5.21-1.noarch.rpm
tests/data/staged-mixed/iso-dest2/FILES/test.txt
tests/data/staged-mixed/staged.yaml
tests/logs/push/test_push/test_typical_push.pulp.yaml
tests/logs/push/test_push/test_update_push.pulp.yaml
tests/push/test_push.py
tests/push/test_upload_sharing.py

When we're used with staged source it's possible for the same file or
RPM to be present in multiple destination dirs. If so, we get one push
item per instance of that file.
The code here did not previously have any special handling for this, so
if the same file was in N dirs then we'd potentially upload it to pulp
N times. Fix it by keeping track of uploaded content and reusing
existing upload futures when possible.

push: fix files potentially being uploaded more than once

---

pubtools/_pulp/tasks/push/items/direct.py

For push items subclassing PulpDirectUploadPushItem, such as modulemd
and productid, it was possible for ensure_uploaded to return a Future
which would complete before the upload had genuinely completed. This
occurred due to an incorrect application of f_map, resulting in an
unexpected nested future.

Fix a subtle error causing direct uploads to not be awaited properly

---

tests/logs/push/test_push_prepush/test_pre_push_no_dest.pulp.yaml
tests/push/test_push_prepush.py

Increase the coverage of this edge case, as it is triggered by certain
Pub commands such as "pub push-rpms --nochannel ..." and wasn't
thoroughly tested before.

tests: add a test covering pre-push with no dest

---

pubtools/_pulp/services/fakepulp.py
tests/shared/test_pulp_task.py

This test involving --fake-pulp would really try to access
`~/.config/pubtools-pulp/fake.yaml`, so it could fail if the caller had
deliberately persisted something weird there. Make sure it uses a clean
environment.

tests: fix one test being affected by local config

---

pubtools/_pulp/services/cachingpulp.py
pubtools/_pulp/tasks/push/items/productid.py
requirements.in
requirements.txt
test-requirements.txt
tests/logs/push/test_push/test_empty_push.pulp.yaml
tests/logs/push/test_push/test_typical_push.pulp.yaml
tests/logs/push/test_push/test_update_push.pulp.yaml
tests/logs/push/test_push_prepush/test_pre_push.pulp.yaml
tests/logs/push/test_push_prepush/test_pre_push_no_dest.pulp.yaml
tests/push/conftest.py
tests/push/test_productid_updates_versions.py

The legacy push code implemented the following side-effect:
when a productid cert is uploaded into a repo, version strings are
extracted from the cert and appended to the product_versions field in
that repo plus other repos with certain matching notes.
That side-effect of productid upload remains important, but was missing
from pubtools-pulp-push. Add it now.

Update product_versions on upload of productid

---

pubtools/_pulp/tasks/push/items/base.py

This log seems too verbose for INFO. The criteria objects tend to be way
too large for casual consumption seeing as we search for hundreds of
items at a time.

logs: demote 'Doing Pulp search' to DEBUG level

---

pubtools/_pulp/tasks/push/items/base.py
pubtools/_pulp/tasks/push/items/rpm.py
tests/push/test_rpm_thin_unit.py

This commit aims to reduce memory usage by throwing away many fields
on Pulp units which are never used during push. In theory, any unit
types could benefit from this; in practice RpmUnit is the only content
type where this currently seems to be worthwhile, as it contains many
fields not used at all during push including some complex ones such
as requires/provides.
(Note it would be even better if we don't query these from Pulp in the
first place, but pulplib.Client does not currently implement that
feature.)

Avoid storing unused fields for RPMs [RHELDST-11376]

---

pubtools/_pulp/services/cachingpulp.py
pubtools/_pulp/services/fakepulp.py
pubtools/_pulp/services/pulp.py
pubtools/_pulp/tasks/common.py
pubtools/_pulp/tasks/push/command.py
pubtools/_pulp/tasks/push/phase/associate.py
pubtools/_pulp/tasks/push/phase/publish.py
pubtools/_pulp/tasks/push/phase/query_pulp.py
pubtools/_pulp/tasks/push/phase/update.py
pubtools/_pulp/tasks/push/phase/upload.py
requirements.in
requirements.txt
test-requirements.txt
tests/fake/test_fake_persistence.py
tests/push/conftest.py
tests/push/test_associate_item_order.py
tests/push/test_push_fake_client.py
tests/push/test_upload_sharing.py
tests/shared/test_pulp_cache.py

Sharing the same client between all phases of push has the following
issue: the client internally can only have so many HTTP requests in
flight to Pulp at once. If all of those requests are being used up by
one phase then other phases depending on requests will be unable to
make progress.
In the worst-case scenario this could lead to a deadlock. This has not
been observed in production today, but it becomes more likely when
reducing the queue size as seen in #134. Fix it by letting each phase
use its own client which cannot interfere with the progress of other
phases.
One downside of this is that the caching pulp client used during push
will now be less effective, as cached values can't be shared between
phases.
Requires some refactoring of --pulp-fake support to ensure that all fake …

refactor: make each push phase use own pulplib client

---

pubtools/_pulp/tasks/push/phase/base.py
tests/push/test_associate_item_order.py

There are still memory usage issues with large push tasks.
After doing some analysis and testing I found that the size of each
future is much larger than I'd expected, around 3.3KiB each on python2
(and roughly half of that on py3).
The number of futures which will exist at any one time is roughly
expected to be some multiple of this tunable. The 10,000 number had no
specific calculations behind it and was far too optimistic.
The new number of 200 is set according to some rough estimates that a
number of 2000 would end up consuming roughly 200MB of memory for Future
objects, and then cutting it further by a factor of 10 to get a generous
safety margin.
One unit test needs a larger queue size because the test is written in a
way which will deadlock otherwise.

tuning: slash default queue size significantly [RHELDST-11374]

---

pubtools/_pulp/tasks/push/phase/base.py
tests/push/test_phase_limits.py

For a phase using put_future_outputs there are effectively two levels of
queue for the output:
1. The phase's proper out_queue (connected to the next phase)
2. A "queue" of futures waiting to put a value on out_queue
These both need to have some constraints on their size to avoid
unreasonable memory usage if we're doing a large push. Previously, (1)
was constrained by the queue size but (2) was not. This commit
refactors the code so that (2) is also constrained, avoiding memory
usage problems.

Fix an internal queue able to grow unbounded [RHELDST-11375]

---

pubtools/_pulp/tasks/common.py
pubtools/_pulp/tasks/push/phase/publish.py
pubtools/_pulp/ud.py
tests/ud/test_ud_cache_client.py

Currently, UD cache flush only flushes repos after publish.
This patch adds errata flushes as well to the UD cache flush
post publish.

Added errata flush in the UD cache flush step post publish

---

pubtools/_pulp/ud.py

Several tasks have failed to flush the UD Cache, for both repo and errata data types. Previous investigations pointed to an issue with the /internal/rcm/flush-cache endpoint, which is an API managed by teamnado. Teamnado folks have said the host running this endpoint has had some issues. Between this info, the fact that the task can succeed when retried later and the exceptions that occur, I believe the intermittent host unavailability is the root issue.
This PR duplicates the same changes I made in pub-utils, increasing the total duration over which retries are carried out. If the root cause of failures is due to intermittent outages, extending the waiting time between retries should allow the issue to pass.

Increase retry backoff RHELDST-9957

---

pubtools/_pulp/tasks/push/items/erratum.py
tests/logs/push/test_push/test_nopublish_push.pulp.yaml
tests/logs/push/test_push/test_typical_push.pulp.yaml
tests/logs/push/test_push/test_update_push.pulp.yaml

Pulp maintains the pkglist for (erratum_id, repo) pair. If an
erratum is uploaded for an existing erratum, it's overwritten if
repo is the same, else is appended.
Currently, the erratum is uploaded to one of the repos picked
randomly from the destination list. This messed up the pkglist
as the packages that were modified in the new erratum upload did't
reflect in the package list as the list is appended rather than
modified/overwritten.
Hence, this patch ensures that the erratums are always uploaded to
the all-rpm-content repo to have the same (erratum_id, repo) pair
generating a consistent pkglist.

Erratums are always uploaded to all-rpm-content repo

---

.github/workflows/tox-test.yml
tox.ini

To enable SAST scanning on this repository, Bandit has been added into the tox.ini and .github/workflows/tox-tests.yml files. Two tests are executed in the pipeline: bandit-exitzero and bandit.
The first scan lists all findings of low severity or higher and always passes due to the "exit-zero" option. This will allow tracking of low severity findings without stopping code from being merged in.
The second scan lists all findings of medium severity or higher and will fail the pipeline if any issues have been introduced.

Add bandit SAST scanning job to the CI [RHELDST-12093]

---

pubtools/_pulp/tasks/push/phase/constants.py

A timeout must be set for all phases here for the reasons explained in the comment, even though in practice we don't really expect that timeout to ever be reached.
Problem: the earlier value worked out to about ~55 hours and it is genuinely possible for some push tasks to take that long during execution, resulting in a spurious timeout as happened in Pub task 545951.
Bump it up by 10x. The new value is about 23 days which surely ought to be enough...

Increase default phase timeout

---

.github/workflows/pip-compile.yml
.github/workflows/tox-test.yml

Github are updating ubuntu-latest runner to use ubuntu 22.04.
This caused two problems in our workflows:
- setup-python can't install py2.7 on ubuntu 22.04, so make that config
stick with ubuntu 20.04
- pip-compile workflow requested python 3.9 but tox pip-compile env
referred to python 3.8. This happened to work on ubuntu 20.04 because
python 3.8 was always installed there by default, but this is no
longer the case, so the mismatch must be corrected.

gh-actions: fix issues with ubuntu 22.04

---

pubtools/_pulp/tasks/push/phase/base.py
pubtools/_pulp/tasks/push/phase/buffer.py
pubtools/_pulp/tasks/push/phase/context.py
requirements.in

Fix two problems with 'monotonic' dependency:
- it should not be required on python 3, since time.monotonic can be used instead
- it was used without declaring it as a dependency. This worked until now because it was a transitive dependency via at least pubtools-pulplib and more-executors. However, those projects now have new releases available which no longer depend on 'monotonic', so it will no longer be pulled in transitively.

Fix monotonic dependency issues

---

.github/workflows/tox-test.yml
legacy.constraints
pubtools/_pulp/arguments.py
pubtools/_pulp/tasks/push/items/rpm.py
pubtools/_pulp/tasks/push/phase/base.py
pubtools/_pulp/tasks/push/phase/context.py
requirements.in
setup.py
tox.ini

After Supercharge Pub 3 was delivered, Python 2 support is no longer required in it's dependencies as well. Dropping Python 2 will make the repos easier to maintain and will speed up Tox and Github Actions since some steps can be removed.

Drop Python2 support

---

pubtools/_pulp/services/pulp.py
tests/push/test_push.py
tests/shared/test_pulp_task.py

With the move to certificates and read-only passwords based authentication, the following were implemented:
- adds --pulp-certificate and --pulp-certificate-key arguments
- supports single file (e.g. .pem) or multiple files (e.g. .cert,.key)  certificates
- supports looking up the cert/key path via the get_cert_key_paths hook defined here: https://release-engineering.github.io/pubtools/hooks.html

Add PKI support for pulp client

---

CHANGELOG.md
pubtools/_pulp/tasks/fix_cves.py
tests/fix_cves/test_fix_cves.py

Added UD cache flush of Erratum object in CVE fix task. With this fix Erratum related to given CVE should be available on Customer portal pages without delay.

UD cache flush for Erratum in CVE fix task [RHELDST-16262]

---

CHANGELOG.md
pubtools/_pulp/cdn.py
pubtools/_pulp/services/__init__.py
pubtools/_pulp/services/cdn.py
pubtools/_pulp/tasks/common.py
tests/cdn/test_cdn_client.py
tests/logs/publish/test_publish/test_repo_publish_cache_cleanup_with_arl.jsonl
tests/logs/publish/test_publish/test_repo_publish_cache_cleanup_with_arl.txt
tests/publish/test_publish.py

This change introduces a CDN client that is used for generating ARLs
that are required for a complete CDN cache purging on certain environments.
Flushing CDN cache by ARLs is enabled only if CDN-related arguments are
passed via CLI. ARLs are generated according to provided templates, only
the TTL value is requested for each path from CDN.

Flush CDN cache by ARL [RHELDST-17152]

---

.github/workflows/docs.yml
.github/workflows/tox-test.yml

This became broken by the release of pip 23.1 and virtualenv 20.21.1. Details on bug report:
junaruga/rpm-py-installer#276
Until there is a proper resolution, pin to an older virtualenv to avoid the issue.
Since the relevant deps here are used during installation of tox itself, the pinning unfortunately cannot be done using the requirements files consumed from within tox.

Fix CI failure installing rpm-py-installer

---

pubtools/_pulp/tasks/publish.py
tests/logs/publish/test_publish/test_publish_repos_not_published_before_a_datetime.jsonl
tests/logs/publish/test_publish/test_publish_repos_not_published_before_a_datetime.txt
tests/logs/publish/test_publish/test_publish_repos_published_before_a_datetime.jsonl
tests/logs/publish/test_publish/test_publish_repos_published_before_a_datetime.txt
tests/publish/test_publish.py

Pub allows users to provide a datetime value for the published-before argument in the publish command, but the library implementation didn't accept it. This change adds in the extra format.

Published-before should accept datetime [RHELDST-12600]

---

pubtools/_pulp/tasks/push/items/base.py

The code here is responsible for logging a summary of a successfully completed copy. The intent is to do this only when a copy succeeded, hence the f.exception() check. However, f.exception() itself raises an exception if the future was cancelled which would generate a lot of log spam.
Fix it to do the logging only if the future succeeded, per the original intent.

Reduce log spam for cancelled copy tasks

---

pubtools/_pulp/tasks/push/items/base.py
pubtools/_pulp/tasks/push/phase/associate.py
pubtools/_pulp/tasks/push/phase/constants.py
tests/logs/push/test_association_race/test_association_race.pulp.yaml
tests/push/test_association_race.py

During the association phase of push we first list the origin repos and then a while later we attempt to copy the items from origin repos to all other desired repos. Since the items can meanwhile be moved between repos, the association can fail on missing items.
We fix this by retrying the copy operation with up-to-date data from pulp.

Retry all failed associations with up-to-date data

---

pubtools/_pulp/cdn.py
pubtools/_pulp/tasks/common.py
tests/cdn/test_cdn_client.py
tests/logs/clear_repo/test_clear_repo/test_clear_file_repo.txt
tests/logs/clear_repo/test_clear_repo/test_clear_yum_repo.txt
tests/logs/delete/test_delete_advisory/test_delete_advisory.txt
tests/logs/delete/test_delete_advisory/test_delete_advisory_in_multiple_repos.txt
tests/logs/delete/test_delete_advisory/test_delete_advisory_no_repos_provided.txt
tests/logs/delete/test_delete_packages/test_delete_files.txt
tests/logs/delete/test_delete_packages/test_delete_modules.txt
tests/logs/delete/test_delete_packages/test_delete_rpms.txt
tests/logs/delete/test_delete_packages/test_delete_unsigned_rpms.txt
tests/logs/fix_cves/test_fix_cves/test_fix_cves_with_cache_cleanup.txt
tests/logs/publish/test_publish/test_repo_publish_cache_cleanup.txt
tests/logs/publish/test_publish/test_repo_publish_cache_cleanup_with_arl.txt

Even though cache flush logs enabled right now are quite verbose, they're missing the most vital info: for which URLs and ARLs did we flush cache.
Log those at INFO level, and decrease a less useful log down to DEBUG level.

Log URLs/ARLs during Akamai cache flush

---

pubtools/_pulp/services/cdn.py
tests/logs/publish/test_publish/test_repo_publish_cache_cleanup_with_arl.txt
tests/publish/test_publish.py

The --cdn-arl-template argument can be used to pass multiple ARL templates, which in practice is needed.
The argument was declared as nargs='*', which means the way it's expected to be used is:
--cdn-arl-template arg1 arg2 arg3 ...
However, the usual convention[1] for list-style arguments in our tools, and the one expected by Pub, is instead:
--cdn-arl-template arg1 \
--cdn-arl-template arg2 \
--cdn-arl-template arg3 ...
So that's how arguments were being passed.
Problem: the latter argument style was accepted, but *only the last argument had any effect*. This meant, for any target configured with multiple ARL templates, only the last one in the list was being used.
Fix the argument handling to support the usual convention (while remaining backwards-compatible).
This issue has always been …

Make --cdn-arl-template argument work as expected by Pub [RHELDST-20512]

---

pubtools/_pulp/cdn.py
tests/cdn/test_cdn_client.py

Previously the TTL extraction was implemented in such way that it could potentially extract the wrong value, if the URL path contained a component that also matched the regex.
This commit changes the re.match() to re.search(), which ensures it will find the first occurrence of the match.

Fix TTL extraction [RHELDST-20510]

---

pubtools/_pulp/tasks/garbage_collect.py

During QA testing we found a bug in the Pulp API which means that batching will not work. This change should be removed until the bug in the Pulp API has been resolved.

Remove garbage collect batching [RHELDST-20725]

---

pubtools/_pulp/tasks/garbage_collect.py
tests/garbage_collect/test_garbage_collect.py

We want to do garbage collection in batches since doing it all at once can cause OOM exceptions. The original attempt used the limit value in criteria submitted to the unassociation endpoint, which did not work. This change instead creates batches using unit searching instead. The size of the batches can be changed by setting the
PUBTOOLS_PULPLIB_PAGE_SIZE env-var.

Do batching with unit IDs [RHELDST-20725]

---

pubtools/_pulp/tasks/clear_repo.py
pubtools/_pulp/tasks/common.py
pubtools/_pulp/tasks/copy_repo.py
pubtools/_pulp/tasks/delete.py
setup.py
tests/copy_repo/test_copy_repo.py
tests/fix_cves/test_fix_cves.py
tests/shared/test_pulp_repo_op_task.py
tests/shared/test_pulp_task.py
tests/shared/test_task_interface.py

Given a list of comma-separated pairs of repos, copy-repo will copy content from the first to the second in the pair. Supports --skip and --content-type.
`copy-repo --target <x> src_a,dst_a src_b,dst_b`

Implement copy_repo entry point [RHELDST-549]

---

pubtools/_pulp/tasks/garbage_collect.py
tests/garbage_collect/test_garbage_collect.py

While ideally we'll only clean up all-rpm-content older than 30 days, to be sure pre-push content is available, let's shorten it to 14 days to alleviate the build-up in all-rpm-content repos until a long-term solution for that is in place.

Reduce default arc_threshold of garbage collect [RHELDST-22675]

---

.github/workflows/tox-test.yml

Jobs failed while uploading the coverage report to Codecov as it failed to get build info from Github. There have been some rate-limiting by Github on
tokenless access by Github, hence Codecov couldn't get the required info from the APIs. So, add the
Codecov token to upload the reports smoothly.

Add Codecov token for uploading coverage reports

---

pubtools/_pulp/services/fakepulp.py
pubtools/_pulp/tasks/push/items/__init__.py
pubtools/_pulp/tasks/push/items/base.py
pubtools/_pulp/tasks/push/items/erratum.py
pubtools/_pulp/tasks/push/items/rpm.py
pubtools/_pulp/tasks/push/phase/upload.py
tests/fake/test_fake_persistence.py
tests/logs/push/test_association_race/test_association_race.pulp.yaml
tests/logs/push/test_push/test_empty_push.pulp.yaml
tests/logs/push/test_push/test_nopublish_push.pulp.yaml
tests/logs/push/test_push/test_typical_push.pulp.yaml
tests/logs/push/test_push/test_update_push.pulp.yaml
tests/logs/push/test_push_prepush/test_pre_push.pulp.yaml
tests/logs/push/test_push_prepush/test_pre_push_no_dest.pulp.yaml
tests/push/test_pulperratumpushitem.py
tests/push/test_push.py
tests/push/test_push_prepush.py
tests/push/test_upload_sharing.py

Currently, all rpm and errata content is pushed to all-rpm-content repo in each environment. Accumulation in the repos is generating concern for performance. To alleviate the build-up, we'll be splitting content between several repos; 'all-rpm-content-XX' for rpms and 'all-erratum-content-YYYY' for errata.
This change refactors the upload_repo and upload_context to reflect this split. It does not include validation for the errata year range, as that feels like a specific implimentation detail.

Update upload_repo for arc split [RHELDST-23264]

---

.github/workflows/tox-test.yml

Codecov-action v4 requires token for upload. However,
it supports tokenless uploads for the PRs on forks to
upstream public repos.

Update codecov-action to v4 for tokenless uploads from PR on forked repos

---

pubtools/_pulp/services/fakepulp.py

frozendict is only an instance of dict *sometimes* (depending on whether the pure-python implementation is used), so for this branch to consistently apply on all kinds of dict we need to match on both frozendict and dict.

Fix missing coverage in fakepulp

---

pubtools/_pulp/tasks/push/items/erratum.py
tests/push/test_pulperratumpushitem.py
tests/push/test_push.py

While investigating another issue I stumbled across this logic. I imagine it'd be the same case for the new all-erratum-content repos

Add all-erratum-content to publish exclusions

---

pubtools/_pulp/tasks/garbage_collect.py
tests/garbage_collect/test_garbage_collect.py

In commit 545991d4e5106f52cee22c55e46f1eab34f823ae the arc_threshold was reduced as a temporary solution for accumulation of content in all-rpm-content repos. Now that a permanent solution has been implemented, let's revert it to the original value.

Restore garbage-collect arc_threshold to 30 (days) [RHELDST-22676]

---

tests/publish/test_publish.py

Multiple repos in the publish and cache flush step may generate a different sequence of logs in different runs, that fails the tests. Hence, this patch ensures to sort the repos to publish step generating a consistent log.

Generate consistent repo sequence in publish test logs

---

src/pubtools/_pulp/tasks/delete.py
tests/delete/test_delete_packages.py
tests/logs/delete/test_delete_packages/test_delete_modules.txt

Currently, rpms in a module are deleted only from the repos where the module exists when a module is deleted. This leaves the rpms from the module in other repos even after module was deleted e.g. modules are present in main rpm repo but the related rpms could be in other repos like source, debug etc. On deletion of the module, rpms from only the main repo were deleted and not from source, debug etc.
This ensures the rpms are deleted from all the provided repos once it's established that module is present in one of the provided repos.

Remove rpms in the modules from all the provided repos [RHELDST-13651]

---

src/pubtools/_pulp/tasks/delete.py
tests/delete/test_delete_packages.py
tests/logs/delete/test_delete_packages/test_delete_modules.jsonl
tests/logs/delete/test_delete_packages/test_delete_modules.txt

Repos with modules were only getting published after deleting the modules. However, there were artifacts from the modules that were deleted from other repos as well. Hence, include those repos to publish when modules are deleted.

Publish all affected repos while deleting modules [RHELDST-13651]

---

src/pubtools/_pulp/tasks/copy_repo.py
tests/copy_repo/test_copy_repo.py
tests/logs/copy_repo/test_copy_repo/test_copy_invalid_content_type.txt
tests/logs/copy_repo/test_copy_repo/test_copy_repo_criteria.txt
tests/logs/copy_repo/test_copy_repo/test_copy_repo_multiple_content_types.txt
tests/logs/copy_repo/test_copy_repo/test_invalid_content_type.txt

Copy-repo previously made copy calls for each content type. Lots of Pulp tasks were spawned with this creating a big queue and slowing down the operations. Hence, this updates copy-repo to make only two copy calls, one for rpm and other for non-rpm content types.
Non-rpm content type units are smaller in count and unit_fields are smaller in size, hence they are all clubbed in the same call ignoring the unit_fields.
Also, non-rpm content type units are copied first as they may have modulemd units, which should be copied before the corresponding modular rpm units to avoid those rpms being visible to user without modulemd units in case of failure or partial copy.

copy-repo makes only two copy calls for a repo pair [RHELDST-28235]

---

src/pubtools/_pulp/tasks/copy_repo.py

copy_repo creates a criteria matching the content_type_id for non-rpm content types. However, in Pulp the type_ids filter with empty type_ids list included all the content types in the result. Hence, the copy-repo copied all the content types when requested only for rpms, as it generated an empty type_ids list for non-rpms. Hence, this adds a check to skip empty type_ids/content_type_id list.

Fixed copy_repo copied all content types when copying only rpms

---

src/pubtools/_pulp/tasks/copy_repo.py

Copy_repo waits for the complete copy of non-rpm content before copying rpm content. However, there were some instances where previous repo pair was sent for non-rpm content copy when multiple repo pairs were provided.
Lambda functions seems to be the reason for the error as they resolve the values during execution rather than creation, hence might be picking incorrect values. This patch replaces it with a modified partial function method that resolves the values during creation instead of execution.

Fix copy_repo sending incorrect repo pairs when providing multiple pairs

---

docs/copy-repo.rst
docs/index.rst

Add documentation page for the copy-repo task in the pubtools-pulp docs.

Add docs page for copy-repo [RHELDST-28512]

---

src/pubtools/_pulp/tasks/copy_repo.py

Add docstring to the CopyRepo class for completing the docs generation.

Add a docstring for copy-repo [RHELDST-28512]

---

requirements.in
src/pubtools/_pulp/tasks/push/items/comps.py
src/pubtools/_pulp/tasks/push/items/file.py
src/pubtools/_pulp/tasks/push/items/modulemd.py
src/pubtools/_pulp/tasks/push/items/productid.py
src/pubtools/_pulp/tasks/push/items/rpm.py
tests/push/test_upload_sharing.py

pushitem content method added in latest pushsource update returns a file-like object with the item bits that may be used for upload. This decouples the source of the items and expectation to exist as a file on local fs.
Note: This PR will be applicable after the changes to `pushsource` are merged
https://github.com/release-engineering/pushsource/pull/643

Use pushitem content to upload

---

src/pubtools/_pulp/tasks/common.py
src/pubtools/_pulp/ud.py
tests/clear_repo/test_clear_repo.py
tests/copy_repo/test_copy_repo.py
tests/delete/test_delete_advisory.py
tests/delete/test_delete_packages.py
tests/fix_cves/test_fix_cves.py
tests/publish/test_publish.py
tests/ud/test_ud_cache_client.py

Previously, during each Flush UD cache step, the Eng ID for each flushed repository was also flushed. This resulted in repeated flushes of the same Eng ID.
It turns out that flushing the Eng ID is not necessary at all, and that just flushing the repos should be enough to keep the UD up to date.

Remove EngID flush [RHELDST-29701]

---

src/pubtools/_pulp/tasks/common.py
src/pubtools/_pulp/ud.py
tests/clear_repo/test_clear_repo.py
tests/copy_repo/test_copy_repo.py
tests/delete/test_delete_packages.py
tests/fix_cves/test_fix_cves.py
tests/publish/test_publish.py
tests/ud/test_ud_cache_client.py

Previously, the UD cache for an eng product ID was flushed whenever it was found in a repo. This functionality was removed, as it put heavy load on the UD cache's API. We later found the product ID should in fact be flushed.
This change adds back in the UD cache flushing for eng product IDs, but makes sure each ID is only flushed once, rather than flushed for each repo it's in.

Flush engproduct ID once [RHELDST-30255]
